name: Build and Push Image
on: [push]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build image
        run: docker build -t ghcr.io/cacapretty/build-image-github .

      - name: Login to GitHub Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u cacapretty --password-stdin

      - name: Push Image
        run: docker push ghcr.io/cacapretty/build-image-github
